### PR TITLE
Create customer_view.html

### PR DESCRIPTION
**Pull request by Tank52**
Added a basic html file for customer interaction with the website

### CODE REVIEW

**Comment by BennyWestsyde** [comment]
@Tank52 Can we please merge #13 before we merge this? it will make it so that you can have this view in the right filesystem and ready to test

**Comment by Tank52** [comment]
> @Tank52 Can we please merge #13 before we merge this? it will make it so that you can have this view in the right filesystem and ready to test

sure, it's just a dummy interface anyway. I also "wrote" some php to handle reading the input and generating an sql command, but idk if that should go in the front or back

**Comment by BennyWestsyde** [comment]
Cool. Alright, so I think you're right about putting this in dev/frontend.

Can you go ahead and check the html files currently in all 3 branches? You will find a good jumping off point there.

**Comment by Tank52** [comment]
> So, I think that we can [fully route this thing with Python](https://flask.palletsprojects.com/en/3.0.x/quickstart/). Your file has a php call in it. I'm not sure if we will need to use that. also, we can move this into the file system at [app/templates/customers.html](app/templates/customers.html)

Didn't know flask supports sql queries. Not sure how all that works, but it would be a lot cleaner to just use python for the interface-database interaction. I'll just modify the html files already in the template folder instead of merging this one.

**Comment by BennyWestsyde** [comment]
Okay sounds good

**Pull request closed without merging**
