### PR TITLE
[BACKEND]: Adding Database Funcitonality (TEMPLATE, EVERYONE PLEASE EXAMINE)

### PR DESCRIPTION
**Pull request by BeTheChange07**
backend, please pull the new html

### CODE REVIEW

**Comment by BennyWestsyde** [comment]
> backend, please pull the new html

are we trying to pull the frontend into the backend?

**Review by Tank52 — COMMENTED** [review]
Are some packages missing in requirements.txt?

**Review by BeTheChange07 — COMMENTED** [review]
missing needed requirements installs. added in the most recent commit

**Review by Tank52 — APPROVED** [review]
looks good

**Comment by BennyWestsyde** [comment]
We should merge this after our meeting @UTD-4347-Databosses/everyone

**Pull request closed without merging**
